[tool.poetry]
name = "explorer-github-diff-checker"
version = "0.2.0"
description = "Diff your Ethereum smart contracts code from GitHub against Blockchain explorer verified source code."
authors = ["Azat Serikov <azatsdev@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/lidofinance/diffyscan"

keywords = ["ethereum", "diff", "sources"]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.31.0"
termtables = "^0.2.4"

[tool.poetry.dev-dependencies]

[tool.poetry.group.dev.dependencies]
black = "^24.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
